export const clothesData = [
  {
    id: "1",
    quantity: 0,
    offer: 0,
    name: "Men's T-Shirt",
    subtitle: "Comfortable and stylish men's t-shirt",
    brand: "XYZ Apparel",
    category: "Shirt",
    price: 19.99,
    countInStock: 0,
    images: ["/images/2.jpg", "/images/3.png"],
    rating: 4.5,
    numReviews: 10,
    description:
      "A comfortable and stylish men's t-shirt made from high-quality cotton fabric.",
  },
  {
    id: "2",
    quantity: 0,
    offer: 39,
    name: "Women's Blouse",
    subtitle: "Fashionable women's blouse with elegant patterns",
    brand: "ABC Fashion",
    category: "Shirt",
    price: 29.99,
    countInStock: 25,
    images: ["/images/4.jpg", "/images/5.jpg"],
    rating: 4.0,
    numReviews: 8,
    description:
      "A fashionable women's blouse with elegant patterns and a perfect fit.",
  },
  {
    id: "3",
    quantity: 0,
    offer: 31,
    name: "Men's Polo Shirt",
    subtitle:
      "Classic men's polo shirt, suitable for both casual and semi-formal occasions",
    brand: "XYZ Apparel",
    category: "Shirt",
    price: 24.99,
    countInStock: 20,
    images: ["/images/6.jpg", "/images/7.jpg"],
    rating: 4.2,
    numReviews: 12,
    description:
      "A classic men's polo shirt, suitable for both casual and semi-formal occasions.",
  },
  {
    id: "4",
    quantity: 0,
    offer: 12,
    name: "Women's Dress",
    subtitle:
      "Elegant women's dress with a flattering silhouette and beautiful design",
    brand: "Fashionista",
    category: "Dress",
    price: 39.99,
    countInStock: 15,
    images: ["/images/8.jpg", "/images/9.png"],
    rating: 4.8,
    numReviews: 18,
    description:
      "An elegant women's dress with a flattering silhouette and beautiful design.",
  },
  {
    id: "5",
    quantity: 0,
    offer: 5,
    name: "Men's Jeans",
    subtitle:
      "Classic men's jeans that offer both style and comfort for everyday wear",
    brand: "Denim Co.",
    category: "Jeans",
    price: 44.99,
    countInStock: 10,
    images: ["/images/10.jpg", "/images/11.jpg"],
    rating: 4.6,
    numReviews: 14,
    description:
      "Classic men's jeans that offer both style and comfort for everyday wear.",
  },
  {
    id: "6",
    quantity: 0,
    offer: 45,
    name: "Women's Leggings",
    subtitle:
      "Stretchy and versatile women's leggings suitable for various activities",
    brand: "XYZ Apparel",
    category: "Leggings",
    price: 24.99,
    countInStock: 18,
    images: ["/images/12.jpg", "/images/13.jpg", "/images/14.jpg"],
    rating: 4.3,
    numReviews: 9,
    description:
      "Stretchy and versatile women's leggings suitable for various activities.",
  },
  {
    id: "7",
    quantity: 0,
    offer: 22,
    name: "Men's Hoodie",
    subtitle: "Comfortable and stylish men's hoodie perfect for cooler weather",
    brand: "XYZ Apparel",
    category: "Hoodies",
    price: 34.99,
    countInStock: 22,
    images: ["/images/15.jpg"],
    rating: 4.7,
    numReviews: 20,
    description:
      "A comfortable and stylish men's hoodie perfect for cooler weather.",
  },
  {
    id: "8",
    quantity: 0,
    offer: 11,
    name: "Women's Cardigan",
    subtitle:
      "A cozy and chic women's cardigan that complements various outfits",
    brand: "Fashionista",
    category: "Cardigans",
    price: 39.99,
    countInStock: 12,
    images: ["/images/16.jpg", "/images/17.png"],
    rating: 4.1,
    numReviews: 7,
    description:
      "A cozy and chic women's cardigan that complements various outfits.",
  },
  {
    id: "9",
    quantity: 0,
    offer: 37,
    name: "Men's Shorts",
    subtitle:
      "Stylish and comfortable men's shorts for casual and outdoor activities",
    brand: "XYZ Apparel",
    category: "Shorts",
    price: 29.99,
    countInStock: 28,
    images: ["/images/18.jpg"],
    rating: 4.4,
    numReviews: 16,
    description:
      "Stylish and comfortable men's shorts for casual and outdoor activities.",
  },
];
